### ISSUE TITLE
No Shop provide when starting a new app from template

### ISSUE THREAD

**Issue by rahul138** [Shopify/shopify-app-template-node#1091]
# Issue summary

I am trying to create first shopify app using node. I followed steps https://shopify.dev/apps/getting-started/create
 `npm init @shopify/app@latest` and `npm run dev` but when app starts it stays 'no shop provided'
<img width="1220" alt="Screenshot 2022-10-03 at 2 42 47 AM" src="https://user-images.githubusercontent.com/6511099/193476556-6625ac27-e69e-482f-babd-c1656c15b945.png">

## Expected behavior

It should be able to open app URL with sample data.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.create a new node app using command line following steps https://shopify.dev/apps/getting-started/create
2.  after starting server the app url should be accessible. but the if you click on app url you will see 'No shop provided error'

Or the view recording of the steps to reproduce the issue https://www.loom.com/share/ecbdb8a171ed4215aa74372e250a241f
## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome
- Device: Laptop
- Operating System: Mac

**Comment by SilasGrygier** [comment]
Hi Rahul! I have run into a similar issue and it's because you are not clicking on the shareable link of your app: you probably clicked the link given in your terminal that looks like this:
`backend  | [nodemon] starting node index.js
frontend | 
frontend |   vite v2.9.15 dev server running at:
frontend |   > Network:  http://192.168.0.11:62025/
frontend |   > Local:    http://localhost:62025/
frontend |
frontend |   ready in 894ms.`

But you have to click on the **shareable url** which is provided in the terminal output a few lines above the link that you clicked which looks something like this:

```
Shareable app URL
https://lsff-19-193-11-111.eu.ngrok.io?shop=rahulsShop.myshopify.com&host=someHostname
```

**Comment by devstein** [comment]
Hi I'm also running into a similar issue **when I deploy to production** and try access the app's API from my store. In development, everything works. Any ideas?

**Comment by mkevinosullivan** [comment]
@rahul138 As @SilasGrygier suggested, you should click on the shareable URL to install the app on your store.  From the loom recording you shared, you need to scroll back a little bit to see the URL.

![Screen Shot 2022-10-11 at 10 26 45 AM](https://user-images.githubusercontent.com/56687600/195121993-906e1fc5-d4e4-477f-bcaa-e700a272250e.png)
