### ISSUE TITLE
send HTTP request from external app to this app

### ISSUE THREAD

**Issue by tuanda-mh** [Shopify/shopify-app-template-node#1335]
How can I send an HTTP request from a third app to this app and get a return?

**Comment by paulomarg** [comment]
This app behaves like any other Express app - you can create a route in your `app` in `index.js`, and call it from the other app.

Note that this template sets up middlewares for some routes, that might break requests from other apps. When you add your route, make sure to add it **before** [this line](https://github.com/Shopify/shopify-app-template-node/blob/main/web/index.js#L38).

We only track bugs in this repo, so I'm going to close this issue, since there's no action for us to take here. I'd recommend reaching out in the [Community Forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or in the Shopify developer Slack where other folks might have faced similar problems in their apps.

Hope this helps!
