### ISSUE TITLE
There's no page at this address

### ISSUE THREAD

**Issue by SerhiDi** [Shopify/shopify-app-template-node#602]
After reInstall app, I see this message
`There's no page at this address`
`Check the URL and try again, or use the search bar to find what you need`

All ok locally, with ngrok tunnel.

## Steps to reproduce the problem

1. Create Node App
2. Do simple changes
3. Deploy to hosting (I used Digitalocean)
4. Make changes on App Settings page(change URL and redirect URL to hosting urls)
5. Install app to Development store
6. Delete the app from the Development store
7. Repeat ` Install app to Development store`
8. Get this error.

I tried submitting this app. And QA engineer wrote:
`Your app hasn't implemented authentication through OAuth correctly and can't be reinstalled. Review our` [OAuth documentation](https://shopify.dev/tutorials/authenticate-with-oauth).

Node app use `koa-shopify-auth` - as I see the app have AccessToken, Oauth working.

What means `hasn't implemented OAuth correctly`?
I think Shopify doesn't delete some app data from shop on app deletion.

**Comment by SerhiDi** [comment]
Install app - `ROUTE ACTIVE_SHOPIFY_SHOPS {}`
Open app -  `ROUTE ACTIVE_SHOPIFY_SHOPS { 'trzdevelopment.myshopify.com': 'write_themes,write_script_tags' }`
Remove app - ``

**Comment by SerhiDi** [comment]
```
┃ Shopify.Webhooks.Registry.register response {
┃   success: true,
┃   result: {
┃     data: { webhookSubscriptionUpdate: [Object] },
┃     extensions: { cost: [Object] }
┃   }
┃ }

```

**Comment by Sanj718** [comment]
I have the same issue and my app was rejected due to this problem :( any solutions please?

**Comment by anhnt2310** [comment]
I got the same issue :(

**Comment by SerhiDi** [comment]
Hello @paulomarg, thanks for your reply.
As I wrote above base app working locally, with ngrok.
If I create a base app, without any changes. I can install/delete it many times. I used my app few days and everything was fine.

After deployment to hosting, after adding the app link to the app setting on Shopify Partners Dashboard I'm starting to see this error.

**Comment by SerhiDi** [comment]
You can try `shopify deploy heroku`

**Comment by paulomarg** [comment]
Sorry, I missed the part where this was happening after deploying.

The scenario where you delete / reinstall quickly is most likely failing because the webhook wasn't called before you reinstalled the app - as I mentioned it can take a little time for the webhook to actually reach your app, as Shopify needs to process the event and fire the request.

The other scenario, where it fails for a few hours, sounds like a case where the webhook handling is failing in your app, and Shopify is retrying it. You can read more about that in our [documentation on webhooks](https://shopify.dev/tutorials/manage-webhooks#creating-an-endpoint-for-webhooks). Shopify will retry failed webhook calls once every roughly 2h to see if they go through.

**Comment by SerhiDi** [comment]
Ok, why webhook not working in the base NodeJS app, after deploying? How I can prevent this? Which code missed in the current version of `shopify-node-app`?

**Comment by anhnt2310** [comment]
@paulomarg  I saw ```/webhooks``` called, but my ```await Shopify.Webhooks.Registry.process(ctx.req, ctx.res)``` can't be resolved. Is there anything I missed ?

**Comment by anhnt2310** [comment]
@paulomarg In the tutorial, it's a specified API version, but in my code, I can't do that because Typescript warning, so I don't add that property and register still successfully, Do it affect? 

I saw ```/webhooks``` called, but my ```await Shopify.Webhooks.Registry.process(ctx.req, ctx.res)``` can't be resolved. Is there anything I missed ?



Tutoiral: 
![image](https://user-images.githubusercontent.com/80698274/114491251-86e61e00-9c40-11eb-8ff0-e3184d7addb8.png)

My code:

![image](https://user-images.githubusercontent.com/80698274/114491311-a2e9bf80-9c40-11eb-8975-f98fe8e0fe56.png)

Warning Typescript:

![image](https://user-images.githubusercontent.com/80698274/114491646-21466180-9c41-11eb-9429-f386e3145eb6.png)

**Comment by Sanj718** [comment]
I feel like Shopify.Webhooks.Registry.process is not firing the webhookHandler which was given in afterAuth().
So, this was my possible work around and my app was approved by shopify review today. 

![image](https://user-images.githubusercontent.com/7362855/114624588-f3800d80-9c7e-11eb-9ffb-f0a157d8b49e.png)

**Comment by SerhiDi** [comment]
@Sanj718 hello,
I tried your solution in two projects, but still seeing this error.

**Comment by Sanj718** [comment]
@SerhiDi hello, the problem is that your shop is not beeing deldted from active_shopify_shops. If you restart your server in heroku installation will work again since active shops const will be empty. So, can you try to console log something befores Shopify.Webhooks....Process? And see if webhook is beeing triggered via heroku logs? It should trigger after 5 seconds you have deleted the app. 

If yes you shoul be able to find shop name in incoming request as i did.

**Comment by SerhiDi** [comment]
@Sanj718, thank you.
I added your code example and restart my remote server ().
```
      const shop = ctx.request.header['x-shopify-shop-domain'];
      delete ACTIVE_SHOPIFY_SHOPS[shop];

      console.log(`Webhook processed, returned status code 200`);
```
After app deletion, I see this log:
`Webhook processed, returned status code 200``

I tried to reinstall the app a few times, all working now. I will try to send my app to review again.

@paulomarg, can you check this code example?
And make the appropriate changes in the `shopify-app-node` boilerplate if they are needed.

**Comment by Geebrox** [comment]
> **Note**: While writing point 4 above, something came to mind: whenever you reload your server, the `Shopify.Webhooks.Registry` object is reset, so it won't be able to `process` webhooks until the corresponding `register` call is made. So, if you're testing webhooks, **please make sure to go to `/auth?shop=...` _before_** trying to uninstall the app to make sure the handler has been loaded into the registry.

@paulomarg As I understand if the server restarts all information about webhooks will be deleted. What if the server goes into maintenance or restarts for other reasons?
The only thing that comes to mind:  We should fetch all stores from DB and reregister webhooks again. Is this the only way?

**Comment by keidarcy** [comment]
`webhookHandler` seems never called by `Shopify.Webhooks.Registry.process`

**Comment by xroussel** [comment]
Same issue here, @Sanj718 solution worked for me thank you!

**Comment by blacktopdev** [comment]
Hello there
I got same error during reinstall app
I am working laravel shopify app 
please help me

**Comment by TonySCruze** [comment]
Whats the resolution for this this issue where reinstalling apps under development fails with "no page at this address"?

**Comment by Sanj718** [comment]
You have to re-register your webhooks everytime you reset your server. 

![image](https://user-images.githubusercontent.com/7362855/166729634-679d7e2e-6337-4e9b-ad0f-2ee2ff4ac1cd.png)

**Comment by DilanAzbarga** [comment]
hi there, I was trying to activate the paypal in shopify from the payments section but it gives me this:Check the URL and try again, or use the search bar to find what you need.
and i want from you a solution plz help me and thank you very much

**Comment by ELBEQQAL94** [comment]
I see the issue come from, when you uninstalled the app webhook not remove session from database and the issue come from.
Solution: try to rollback all sessions and restart you server

**Comment by Sky-bits** [comment]
> I feel like Shopify.Webhooks.Registry.process is not firing the webhookHandler which was given in afterAuth(). So, this is my possible workaround and my app was approved by shopify review today.
> 
> ![image](https://user-images.githubusercontent.com/7362855/114624588-f3800d80-9c7e-11eb-9ffb-f0a157d8b49e.png)

@Sanj718  i have app in express js i am getting the same Error can answer on it
