### ISSUE TITLE
Registering a simple webhook

### ISSUE THREAD

**Issue by smotched** [Shopify/shopify-app-template-node#682]
# Issue summary
I've been attempting to register a simple webhook for users that want to request their personal data. Tried pretty much everything, and look through every shopify forums on this, "read_customers, write_customers" scopes are in env. The error message is "No webhook is registered for topic customers/data_request"

```javascript
createShopifyAuth({
  async afterAuth(ctx) {

     ...

     const response = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: "/webhooks",
          topic: "customers/data_request",
          webhookHandler: async (payload) => {
               console.log("WEBHOOK FIRED")
          }
     });

     if (!response.success) {
          console.log( `Failed to register webhook: ${response.result}`
     );

     ...

     }
}

```

**Comment by yehorelevator** [comment]
You have to add endpoint to app dashboard
![Uploading Снимок экрана 2021-12-19 в 13.56.31.png…]()

**Comment by smotched** [comment]
they're there, the webhook doesn't register or fire

**Comment by Michael-Gibbons** [comment]
@smotched this is a shot in the dark but I don't think you actually have to register the GDPR webhooks in the code just in the admin, as the topic you're trying to register doesn't actually exist it could be erroring out because of that. 

Also if you're using a body parsing package like `koa-body-parser` make sure you're excluding your webhooks route from it because that could also block incoming webhooks. Here is my approch

```
  server.use(async (ctx, next) => {
    if (ctx.path === "/graphql" || ctx.path === "/webhooks") {
      return await next();
    }
    await bodyParser({
      extendTypes: {
        json: ["text", "text/plain"],
      },
    })(ctx, next);
  });
```

Again unsure if this will help but this is how I resolved a similar situation
